# Generated by Django 2.2.12 on 2020-04-19 20:45

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Poco',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('proprietar', models.CharField(max_length=254)),
                ('orgao', models.CharField(max_length=254)),
                ('data_perfu', models.DateField()),
                ('profundida', models.FloatField()),
                ('q_m3h', models.FloatField()),
                ('equipament', models.CharField(max_length=254)),
                ('geom', django.contrib.gis.db.models.fields.PointField(srid=4326)),
            ],
        ),
    ]
